run_mode: kSim
trigger_mode: kManual
init_motion_enable: true
planner_trigger_lead_time: 0.7
smooth_heading_enable: true
init_motion:
  z_takeoff: 3.0
  z_drop: 1.5
  x_forward: 3.0

# Group related parameters to be shared between nodes.
RobotDynamics:
  v_max: 2.0
  v_init_max: 1.0
  v_homing_max: 2.0
  yaw_rate_max: 0.1
  dt: 0.05
